---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 5.11.0-slim

inputs:
  - name: helionce-git-repo
outputs:
  - name: build_code_output

run:
  path: helionce-git-repo/hce-ci/scripts/build
